/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/images/brain-simple-mesh.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Brain(props) {
  const { nodes, materials } = useGLTF('./images/brain-simple-mesh.gltf')
  return (
    <group {...props} dispose={null} scale={[1,1,1]}>
      <group rotation={[1.45, 0.15, -1.04]}>
        <mesh geometry={nodes['default-mesh'].geometry} material={materials.Pink} />
        <mesh geometry={nodes['default-mesh_1'].geometry} material={materials.Red} />
      </group>
    </group>
  )
}


useGLTF.preload('./images/brain-simple-mesh.gltf')
