export const Alumni = [
    {
        id: `alumni_1`,
        name: "Aryan Verma",
        position:"alumni",
        passout_year: 2022,
        email: "aryanvermaiit@gmail.com",
        linkedin: "https://www.linkedin.com/in/aryan-verma-98a842178",
        github: "https://github.com/Aryan-Verma",
        image: require(`../../../public/images/Alumni/Aryan Verma.jpeg`),
    },
    {
        id: `alumni_2`,
        name: "Siddhesh Shelke",
        position:"alumni",
        passout_year: 2023,
        email: "siddheshshelke015@gmail.com",
        linkedin: "www.linkedin.com/in/siddhesh-shelke/",
        github: "https://github.com/sids-09",
        image: require(`../../../public/images/Alumni/Siddhesh Shelke.jpeg`),
    },
    {
        id: `alumni_3`,
        name: "Aryan Rastogi",
        position:"alumni",
        passout_year: 2023,
        email: "aryan.rastogi13@gmail.com",
        linkedin: "www.linkedin.com/in/aryan-r22",
        github: "http://www.github.com/aryan-r22",
        image: require(`../../../public/images/Alumni/Aryan Rastogi.jpeg`),
    },
    
    {
        id: `alumni_4`,
        name: "Tarun Gupta",
        position:"alumni",
        passout_year: 2023,
        email: "tarungupta360@gmail.co",
        linkedin: "https://www.linkedin.com/in/tarun-gupta-116860178/",
        github: "https://github.com/tarun360",
        image: require(`../../../public/images/Alumni/Tarun Gupta.jpeg`),
    },
    {
        id: `alumni_5`,
        name: "Bharat Gupta",
        position:"alumni",
        passout_year: 2023,
        email: "bharatgupta18001@gmail.com",
        linkedin: "https://www.linkedin.com/in/bharatkgupta",
        github: "https://github.com/Bharatkgupta",
        image: require(`../../../public/images/Alumni/Bharat Gupta.jpeg`),
    },
];
