[
	{
		"Name:": "Ashutosh S.",
		"position:": "Outreach head",
		"email": "cse210001005@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/ashutosh-samantaray-531516249/",
		"github": "https://github.com/A5HU705H",
	},
	{
		"Name:": "G Aakash",
		"position:": "Member",
		"email": "cse210001015@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/g-aakash-6a001523b/",
		"github": "https://github.com/cse210001015",
	},
	{
		"Name:": "Jha Rohan",
		"position:": "Member",
		"email": "ee210002041@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/rohan-jha-aa2177231/",
		"github": "https://github.com/rohanjha04",
	},
	{
		"Name:": "Yatharth Gupta",
		"position:": "Head",
		"email": "cse210001083@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/yatharth-g/",
		"github": "https://github.com/Warlord-K",
	},
	{
		"Name:": "Vishnu V Jaddipal",
		"position:": "Member",
		"email": "cse210001078@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/vishnu-jaddipal-28b407243/",
		"github": "https://github.com/Gothos",
	},
	{
		"Name:": "Madhav Kadam",
		"position:": "Head of Events",
		"email": "cse210001027@iiti.ac.in",
		"linkedin": "",
		"github": "",
	},
	{
		"Name:": "Atharva Nanoti",
		"position:": "Volunteer",
		"email": "cse220001013@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/atharva-nanoti-21973425b",
		"github": "https://github.com/NanoTcodes",
	},
	{
		"Name:": "Soham Pandit",
		"position:": "Volunteer",
		"email": "me220003080@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/soham-pandit-379b35255",
		"github": "https://github.com/Scav6411",
	},
	{
		"Name:": "J. Dinesh",
		"position:": "Volunteer",
		"email": "cse210001026@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/dinesh-kumar-b09852233",
		"github": "https://github.com/Dinesh1102",
	},
	{
		"Name:": "Atharva Mohite",
		"position:": "Member",
		"email": "me200003016@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/atharva-mohite-4368601bb",
		"github": "https://github.com/atharva-mohite",
	},
	{
		"Name:": "Suhana Shaik",
		"position:": "Volunteer",
		"email": "cse220001073@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/suhana-shaik-955671258",
		"github": "https://github.com/tekksick",
	},
	{
		"Name:": "Sai Pranay Deep",
		"position:": "Volunteer",
		"email": "cse220001034@iiti.ac.in",
		"linkedin":
			"https://www.linkedin.com/in/saipranaydeep-jonnalagadda-9b30b225b",
		"github": "https://github.com/saipranaydeep",
	},
	{
		"Name:": "Shivankar Sharma",
		"position:": "Member",
		"email": "ee210002071@iiti.ac.in",
		"linkedin": "",
		"github": "",
	},
	{
		"Name:": "Aakash Sangvikar",
		"position:": "Volunteer",
		"email": "mems210005039@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/aakash-sangvikar/",
		"github": "https://github.com/GitsAakash",
	},
	{
		"Name:": "Lovely",
		"position:": "Volunteer",
		"email": "ee220002046@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/lovely-bhardwaj-89603425b/",
		"github": "https://github.com/lovelybhardwaj",
	},
	{
		"Name:": "Amit Kumar Makkad",
		"position:": "Member",
		"email": "cse200001003@iiti.ac.in",
		"linkedin": "https://in.linkedin.com/in/amit-kumar-makkad-09167b214",
		"github": "https://github.com/amitmakkad",
	},
	{
		"Name:": "Pradeep Kumar Rebbavarapu",
		"position:": "Volunteer",
		"email": "cse220001058@iiti.ac.in",
		"linkedin":
			"https://www.linkedin.com/in/pradeep-kumar-rebbavarapu-820489259/",
		"github": "https://github.com/Pradeep-Kumar-Rebbavarapu",
	},
	{
		"Name:": "Surya karthikeya",
		"position:": "Member",
		"email": "cse210001041@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/surya-karthikeya-327255228",
		"github": "https://github.com/surya1176",
	},
	{
		"Name:": "Ayush Awasthi",
		"position:": "Volunteer",
		"email": "me220003016@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/ayush-awasthi-a232b8254",
		"github": "https://github.com/ayushawasthi24",
	},
	{
		"Name:": "Yash Vashistha",
		"position:": "Member",
		"email": "cse210001082@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/yash-vashistha/",
		"github": "https://github.com/Yashiiti",
	},
	{
		"Name:": "Krish Agrawal",
		"position:": "Member",
		"email": "cse210001034@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/krish-agrawal-472784146/",
		"github": "https://github.com/Krish2208",
	},
	{
		"Name:": "Aadish Jain",
		"position:": "Volunteer",
		"email": "cse220001001@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/aadish-jain-177ab925a/",
		"github": "https://github.com/mapcrafter2048",
	},
	{
		"Name:": "Kaustuv Devmishra",
		"position:": "Volunteer",
		"email": "me220003045@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/kaustuv-devmishra-372868253/",
		"github": "https://github.com/kaustuv-d",
	},
	{
		"Name:": "Tanisha Sahu",
		"position:": "Member",
		"email": "cse210001071@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/tanisha-sahu-197882232/",
		"github": "https://github.com/10isha",
	},
	{
		"Name:": "Samip Shah",
		"position:": "Member",
		"email": "cse210001061@iiti",
		"linkedin": "",
		"github": "",
	},
	{
		"Name:": "Aman Poddar",
		"position:": "Volunteer",
		"email": "ee220002006@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/aman-poddar-55050b26a",
		"github": "",
	},
	{
		"Name:": "Prajakta Darade",
		"position:": "Member",
		"email": "cse210001052@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/prajakta-darade-40b585237/",
		"github": "https://github.com/prajakta-1527",
	},
	{
		"Name:": "Abhinav gangil",
		"position:": "Volunteer",
		"email": "cse220001002@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/abhinav-gangil-193594255",
		"github": "https://github.com/xenom2004",
	},
	{
		"Name:": "Bhavya Contractor",
		"position:": "Member",
		"email": "cse200001018@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/bhavya-contractor-b47784214",
		"github": "https://github.com/bhavyacontractor",
	},
	{
		"Name:": "Khushi Sawla",
		"position:": "Member",
		"email": "ee210002045@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/khushi-sawla-303458222",
		"github": "https://github.com/khushisawla",
	},
	{
		"Name:": "Raina Tathed",
		"position:": "Volunteer",
		"email": "ee220002067@iiti.ac.in",
		"linkedin": "https://www.linkedin.com/in/raina-tathed-5650a025b",
		"github": "https://github.com/Raina-310304",
	},
];
