
export const TeamMembers = [
    {
        id:1,
        name:"Pradeep Kumar.R",
        position:"Volunteer",
        year:2,
        image:require("../../../public/images/me.jpg"),
        branch:"CSE",
        email:"",
        phone:"",
        Linkedin:"",
        github:"",
        facebook:"",
        instagram:"",
        twitter:"",
        location:"",  
    },
    {
        id:2,
        name:"Pradeep Kumar.R",
        position:"Volunteer",
        year:2,
        image:require("../../../public/images/me.jpg"),
        branch:"CSE",
        email:"",
        phone:"",
        Linkedin:"",
        github:"",
        facebook:"",
        instagram:"",
        twitter:"",
        location:"",  
    }
]