export const TeamMembers = [
  {
    id: 1,
    name: "Yatharth Gupta",
    position: "Head",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001083@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/yatharth-g/",
    github: "https://github.com/Warlord-K",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 2,
    name: "Madhav Kadam",
    position: "Head of Events",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001027@iiti.ac.in",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 3,
    name: "Ashutosh S.",
    position: "Outreach head",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001005@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/ashutosh-samantaray-531516249/",
    github: "https://github.com/A5HU705H",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 4,
    name: "Vishnu V Jaddipal",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001078@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/vishnu-jaddipal-28b407243/",
    github: "https://github.com/Gothos",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 5,
    name: "Jha Rohan",
    position: "Member",
    year: 3,
    image: "",
    branch: "EE",
    email: "ee210002041@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/rohan-jha-aa2177231/",
    github: "https://github.com/rohanjha04",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 6,
    name: "G Aakash",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001015@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/g-aakash-6a001523b/",
    github: "https://github.com/cse210001015",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 7,
    name: "Atharva Mohite",
    position: "Member",
    year: 3,
    image: "",
    branch: "ME",
    email: "me200003016@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/atharva-mohite-4368601bb",
    github: "https://github.com/atharva-mohite",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 8,
    name: "Shivankar Sharma",
    position: "Member",
    year: 3,
    image: "",
    branch: "EE",
    email: "ee210002071@iiti.ac.in",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 9,
    name: "Amit Kumar Makkad",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse200001003@iiti.ac.in",
    Linkedin: "https://in.linkedin.com/in/amit-kumar-makkad-09167b214",
    github: "https://github.com/amitmakkad",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 10,
    name: "Surya karthikeya",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001041@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/surya-karthikeya-327255228",
    github: "https://github.com/surya1176",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 11,
    name: "Yash Vashistha",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001082@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/yash-vashistha/",
    github: "https://github.com/Yashiiti",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 12,
    name: "Krish Agrawal",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001034@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/krish-agrawal-472784146/",
    github: "https://github.com/Krish2208",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 13,
    name: "Tanisha Sahu",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001071@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/tanisha-sahu-197882232/",
    github: "https://github.com/10isha",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 14,
    name: "Samip Shah",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001061@iiti",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 15,
    name: "Prajakta Darade",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse210001052@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/prajakta-darade-40b585237/",
    github: "https://github.com/prajakta-1527",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 16,
    name: "Bhavya Contractor",
    position: "Member",
    year: 3,
    image: "",
    branch: "CSE",
    email: "cse200001018@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/bhavya-contractor-b47784214",
    github: "https://github.com/bhavyacontractor",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 17,
    name: "Khushi Sawla",
    position: "Member",
    year: 3,
    image: "",
    branch: "EE",
    email: "ee210002045@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/khushi-sawla-303458222",
    github: "https://github.com/khushisawla",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 18,
    name: "Atharva Nanoti",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse220001013@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/atharva-nanoti-21973425b",
    github: "https://github.com/NanoTcodes",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 19,
    name: "Soham Pandit",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "ME",
    email: "me220003080@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/soham-pandit-379b35255",
    github: "https://github.com/Scav6411",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 20,
    name: "J. Dinesh",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse210001026@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/dinesh-kumar-b09852233",
    github: "https://github.com/Dinesh1102",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 21,
    name: "Suhana Shaik",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse220001073@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/suhana-shaik-955671258",
    github: "https://github.com/tekksick",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 22,
    name: "Sai Pranay Deep",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse220001034@iiti.ac.in",
    Linkedin:
      "https://www.linkedin.com/in/saipranaydeep-jonnalagadda-9b30b225b",
    github: "https://github.com/saipranaydeep",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 23,
    name: "Aakash Sangvikar",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "MEMS",
    email: "mems210005039@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/aakash-sangvikar/",
    github: "https://github.com/GitsAakash",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 24,
    name: "Lovely",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "EE",
    email: "ee220002046@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/lovely-bhardwaj-89603425b/",
    github: "https://github.com/lovelybhardwaj",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 25,
    name: "Pradeep Kumar Rebbavarapu",
    position: "Volunteer",
    year: 2,
    image: require("../../../public/images/Members/me.jpg"),
    branch: "CSE",
    email: "cse220001058@iiti.ac.in",
    Linkedin:
      "https://www.linkedin.com/in/pradeep-kumar-rebbavarapu-820489259/",
    github: "https://github.com/Pradeep-Kumar-Rebbavarapu",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 26,
    name: "Ayush Awasthi",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "ME",
    email: "me220003016@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/ayush-awasthi-a232b8254",
    github: "https://github.com/ayushawasthi24",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 27,
    name: "Aadish Jain",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse220001001@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/aadish-jain-177ab925a/",
    github: "https://github.com/mapcrafter2048",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 28,
    name: "Kaustuv Devmishra",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "ME",
    email: "me220003045@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/kaustuv-devmishra-372868253/",
    github: "https://github.com/kaustuv-d",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 29,
    name: "Aman Poddar",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "EE",
    email: "ee220002006@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/aman-poddar-55050b26a",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 30,
    name: "Abhinav gangil",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "CSE",
    email: "cse220001002@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/abhinav-gangil-193594255",
    github: "https://github.com/xenom2004",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
  {
    id: 31,
    name: "Raina Tathed",
    position: "Volunteer",
    year: 2,
    image: "",
    branch: "EE",
    email: "ee220002067@iiti.ac.in",
    Linkedin: "https://www.linkedin.com/in/raina-tathed-5650a025b",
    github: "https://github.com/Raina-310304",
    facebook: "",
    instagram: "",
    twitter: "",
    location: "",
  },
];
